server:
  port: 8091
spring:
  application:
    name: foam #项目名称
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always #控制台彩色输出
  datasource:
    type: com.zaxxer.hikari.HikariDataSource #配置数据库连接池，Hikari其实是默认连接池

    # H2 Database 配置
    driver-class-name: org.h2.Driver #配置数据库驱动
    url: jdbc:h2:file:~/.foam/db/foam #配置数据库连接地址，第一次运行会自动创建相关文件
    username: root
    password: 123456
    #hikari:
    #  maximum-pool-size: 30
    #  minimum-idle: 10

    # MySQL 配置
  #  driver-class-name: com.mysql.cj.jdbc.Driver
  #  url: jdbc:mysql://127.0.0.1:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  #  username: root
  #  password: 123456

  #H2数据库配置
  h2:
    console:
      settings:
        web-allow-others: true #配置能否远程访问
      path: /h2-console #配置访问地址
      enabled: true #配置项目启动 h2就启动
  jpa:
    hibernate:
      ddl-auto: update  #create：每次运行程序时，都会重新创建表，故而数据会丢失
        #create-drop：每次运行程序时会先创建表结构，然后待程序结束时清空表
        #upadte：每次运行程序，没有表时会创建表，如果对象发生改变会更新表结构，原有数据不会清空，只会更新（推荐使用）
        #validate：运行程序会校验数据与数据库的字段类型是否相同，字段不同会报错
      #none: 禁用DDL处理
    show-sql: true #是否显示sql语句
  servlet:
    multipart: #springboot上传文件大小限制的配置
      max-file-size: 10240MB #单个数据的大小
      max-request-size: 10240MB #总数据的大小
  mvc:
    favicon:
      enabled: false #关闭网页标签上的springboot上小叶子的默认图标
  thymeleaf:
    cache: false
logging:
  level:
    run.halo.app: INFO
  path: ${user.home}/.foam/logs
foam:
  jwt:
    secret: foam@aazzxxcc
  filter:
    allowPaths:
      - /api/post/show
      - /api/admin/about/find
      - /api/comment/info/find
      - /api/file/aliyun/upload
      - /api/admin/login
      - /api/admin/check
      - /api/admin/register
